FROM node:10-alpine as frontend-build

WORKDIR /usr/src/project

COPY frontend/package.json ./
RUN yarn install

COPY frontend/. .

ENV NODE_ENV production
RUN yarn run build

FROM python:3.7-slim
EXPOSE 80

WORKDIR /usr/src/project

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY --from=frontend-build /usr/src/project/dist ./frontend/dist

COPY . .

RUN python manage.py collectstatic --no-input

CMD gunicorn -b 0.0.0.0:$PORT vsstatsproject.wsgi:application
