# Generated by Django 2.1 on 2019-08-22 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, validators=[django.core.validators.URLValidator(schemes=['mongodb'])])),
                ('source_type', models.CharField(choices=[('API', 'API server'), ('BOT', 'Telegram bot')], max_length=3)),
            ],
        ),
    ]
